apiVersion: temporal.io/v1beta1
kind: TemporalNamespace
metadata:
  name: default
  namespace: demo
spec:
  clusterRef:
    name: prod
    namespace: demo
  description: Default namespace
  retentionPeriod: 168h # 7 days
